### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by MP5s** [develslawer/webcalc#4]
Привет, при проверке твоей работы столкнулся с некоторыми проблемами.

### 1. Программа не проходит свои же тесты.
![develslawer1](https://github.com/user-attachments/assets/9e6b7436-207b-4921-8414-b6df6031cc16)
### 3. Пример, когда будет выдаваться ошибка с кодом 422.

> С ошибками 400, 405 проблем у меня не возникло

**Comment by MP5s** [comment]
Дополню: в тестах проблема с application_test.go

**Comment by develslawer** [comment]
исправил ошибку с тестами. Просьба проверить еще раз

примеров на 500 код http-ответа не предусмотрено в тестах потому что ошибка возвращается только в том случае когда сервер не способен корректно обработать запрос (таких случаев с корректными выражениями или некорректным вводом не встречал). Если Вам удастся вызвать 500 код ответа, пожалуйста сообщите, обязательно добавлю в тесты или исправлю ошибку

**Comment by MP5s** [comment]
Спасибо за такой быстрый ответ. Проверил еще раз, проблем не обнаружил
